services:
  frontend:
    image: elekrady/fosha_frontend:latest
    container_name: fosha_frontend
    ports:
      - "${API_URL}:80:80"
    networks:
      - fosha_network

  backend:
    image: elekrady/fosha_backend:latest
    container_name: fosha_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - fosha_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${API_URL}:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: fosha_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fosha_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  fosha_network:

volumes:
  mongo_data: